"""empty message

Revision ID: 25520846a00c
Revises: c4175a1d647b
Create Date: 2020-10-08 16:13:00.990352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25520846a00c'
down_revision = 'c4175a1d647b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('dish_list', sa.String(), nullable=False))
    op.drop_column('orders', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'dish_list')
    # ### end Alembic commands ###
