"""empty message

Revision ID: 60a90aa83d7b
Revises: bcd0934f8756
Create Date: 2020-10-10 21:58:43.725507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a90aa83d7b'
down_revision = 'bcd0934f8756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'client_name')
    # ### end Alembic commands ###
