"""empty message

Revision ID: 8ea7868e50f5
Revises: 60a90aa83d7b
Create Date: 2020-10-10 22:01:02.280859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea7868e50f5'
down_revision = '60a90aa83d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_sum', sa.Float(), nullable=False))
    op.drop_column('orders', 'order_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'order_sum')
    # ### end Alembic commands ###
